### ISSUE TITLE
Проверка задания номер 1

### ISSUE THREAD

**Issue by Kelmyashkin** [Kelmyashkin/vue-course#1]
Компонент Autocomplete

**Comment by xanf** [comment]
Годится, можете закрывать. Единственное замечание: 
```js
        typeof item === 'string' ? item : this.getTextFromItem(item);
```

Так не надо делать. Надо делать наборот - если передали getTextFromItem - вызываем его - иначе нет. А то пользователь передает функцию и строку и недоумевает, почему функция тупо не вызывается. Не надо огорчать разработчика :)

**Comment by Kelmyashkin** [comment]
Я поправил. Остался вопрос, это нормально передавать пропсу с функцией которая вытаскивает из объекта текст для поля? И как я понял нельзя добавить валидатор что если value - object, то getTextFromItem - required. И может выкидывать ошибку, если у нас объект и нет этой функции?

**Comment by xanf** [comment]
Да, нормально
Да, к сожалению нельзя.
Да, можно выкидывать ошибку
